# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d778579d4b3640786a5939bc8b204d621b7ce27f43b0797ff89f49770da4ff84a2c8d79f1fca008288f96d5c112ce727304f14616721a06d799755745e0473c5

test:
  secret_key_base: 0b8e72b22d4c46e008bdab4358f24efd5ec58282ca961dbe9657df27b2c4ea6ead8d3ba3a3edcd9d638cd9fdd95f29d323a58907c0f7418b80e5f8d8f3fc4ae9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
